### ISSUE TITLE
Utilise WooCommerce official _transaction_id as Order Meta

### ISSUE THREAD

**Issue by abdusfauzi** [Billplz/Billplz-for-WooCommerce#6]
https://github.com/Billplz/Billplz-for-WooCommerce/blob/c467a729e355e0c9ff323dccb70f836c1db321fd/billplzWoo.php#L296

On this line, perhaps, we can use `_transaction_id` because this is the official WC order meta and will be shown on Order Page.

Refer sample here:
https://github.com/abdusfauzi/exn-wc-billplz/blob/master/class/class-exn-wc-billplz.php#L284
and here for implementation on Order page
https://github.com/abdusfauzi/exn-wc-billplz/blob/master/class/class-exn-wc-billplz.php#L428

**Comment by wzul** [comment]
https://github.com/Billplz/Billplz-for-WooCommerce/blob/61d2a37cc360cb9e6aa6f77e56f273def7ac2dfb/billplzWoo.php#L309

Since we are calling Get a Bill API to check the bill status (if deleted: hidden state), then, I think it's better to remove the "billplz_url" meta and rely on the Get a Bill API since we can get the URL from that.

So, the _transaction_id will be used instead of billplz_id for storing bill id instead of bill url.

**Comment by abdusfauzi** [comment]
@wzul great!

**Comment by wzul** [comment]
Updated on both GitHub and [WordPress SVN](https://plugins.trac.wordpress.org/browser/billplz-for-woocommerce/trunk/billplzWoo.php?rev=1906029#L296)
